services:
    app.twig_extension:
      class : Mirage\MainBundle\Twig\MirageExtension
      public: false
      tags:
        - { name: twig.extension }
#    mirage_main.example:
#        class: Mirage\MainBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]


