<?php

namespace Mirage\UserBundle\Repository;

/**
 * CharaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharaRepository extends \Doctrine\ORM\EntityRepository
{
}
