<?php

namespace Mirage\UserBundle\Repository;

/**
 * DeckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeckRepository extends \Doctrine\ORM\EntityRepository
{
}
