<?php

namespace Mirage\UserBundle\Repository;

/**
 * DeckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOnlyComponents($idPlayer){
        $query = $this->createQueryBuilder('i')
            ->where('i.idItem > 100000')
            ->andWhere('i.idItem < 200000')
            ->andWhere('i.idPlayer = :idPlayer')
            ->andWhere('i.isEnabled = 1')
            ->setParameter('idPlayer', $idPlayer)
            ->getQuery();

        $components = $query->getResult();
        foreach($components as &$component){
            $component->unsetPlayer();
        }

        return $components;
    }

}
