<?php

namespace Mirage\UserBundle\Repository;

/**
 * IStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IStoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyProgress($idPlayer){
        $query = $this->createQueryBuilder('s')
            ->where('s.idPlayer = :idPlayer')
            ->andWhere('s.isEnabled = 1')
            ->setParameter('idPlayer', $idPlayer)
            ->getQuery();


        return $query->getResult();
    }

}
