<?php

namespace Mirage\UserBundle\Repository;

/**
 * TemporisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemporisRepository extends \Doctrine\ORM\EntityRepository
{


}
