Top:
    prefix : /
    type : annotation
    resource : "@MirageUserBundle/Controller/TopController.php"


Battle:
    prefix : /battle
    type : annotation
    resource : "@MirageUserBundle/Controller/BattleController.php"

Story:
    prefix : /story
    type : annotation
    resource : "@MirageUserBundle/Controller/StoryController.php"

Deck:
    prefix : /deck
    type : annotation
    resource : "@MirageUserBundle/Controller/DeckController.php"

Summon:
    prefix : /summon
    type : annotation
    resource : "@MirageUserBundle/Controller/SummonController.php"

Temporis:
    prefix : /temporis
    type : annotation
    resource : "@MirageUserBundle/Controller/TemporisController.php"

Friend:
    prefix : /friend
    type : annotation
    resource : "@MirageUserBundle/Controller/FriendController.php"

